if node['wordpress']['setup']['admin_password']['from_data_bag']
  data_bag_secret = Chef::EncryptedDataBagItem.load_secret(node['wordpress']['setup']['admin_password']['secret_path'])
  node.set['wordpress']['setup']['admin_password']['value'] = Chef::EncryptedDataBagItem.load(node['wordpress']['setup']['admin_password']['data_bag'], node['wordpress']['setup']['admin_password']['data_bag_item'], data_bag_secret)[node['wordpress']['setup']['admin_password']['data_bag_item_key']]
else
  ::Chef::Recipe.send(:include, Opscode::OpenSSL::Password)
  node.set_unless['wordpress']['setup']['admin_password']['value'] = secure_password
  Chef::Log.warn("Autogenerated password for #{node['wordpress']['setup']['admin_user']}: #{node['wordpress']['setup']['admin_password']['value']}.\nConsider to change it ASAP!")
end

execute 'wp core install' do
  action :run
  command %Q|#{Chef::Config[:file_cache_path]}/wp \
    --path='#{node['wordpress']['dir']}' \
    core install \
    --title='#{node['wordpress']['setup']['title']}' \
    --admin_user='#{node['wordpress']['setup']['admin_user']}' \
    --admin_password='#{node['wordpress']['setup']['admin_password']['value']}' \
    --admin_email='#{node['wordpress']['setup']['admin_email']}' \
    --url='#{node['wordpress']['setup']['url']}'|
  not_if %Q|#{Chef::Config[:file_cache_path]}/wp \
    --path='#{node['wordpress']['dir']}' \
    core is-installed|
end
