driver: 
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8081}]
    - ["private_network", {ip: "192.168.34.35"}]
driver_config:
  box: opscode-ubuntu-14.04

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      customize:
        memory: 2048
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[wordpress]
    attributes:
      mysql:
        server_root_password: "Please-Dont-Use-In-Production"
        server_debian_password: "Please-Dont-Use-In-Production"
        server_repl_password: "Please-Dont-Use-In-Production"